/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  // Dark mode disabled - TUMS uses light theme only (data-theme="tums")
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#3d5a4f',
          light: '#4d6f62',
          dark: '#2d4a3f',
        },
        secondary: {
          DEFAULT: '#b8935f',
          light: '#c9a570',
          dark: '#a07d4f',
        },
        success: '#28a745',
        warning: '#ffa726',
        danger: '#dc3545',
        info: '#17a2b8',
        neutral: '#6c757d',
        background: '#f8f9fa',
        card: '#ffffff',
        border: '#dee2e6',
      },
      fontFamily: {
        cairo: ['Cairo', 'Segoe UI', 'Tahoma', 'sans-serif'],
        roboto: ['Roboto', 'Segoe UI', 'sans-serif'],
      },
      borderRadius: {
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
      },
      boxShadow: {
        'sm': '0 2px 4px rgba(0,0,0,0.08)',
        'md': '0 4px 8px rgba(0,0,0,0.1)',
        'lg': '0 8px 16px rgba(0,0,0,0.12)',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        // TUMS Light Theme (default)
        tums: {
          "primary": "#3d5a4f",
          "primary-content": "#ffffff",
          "secondary": "#b8935f",
          "secondary-content": "#ffffff",
          "accent": "#4d6f62",
          "accent-content": "#ffffff",
          "neutral": "#6c757d",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f8f9fa",
          "base-300": "#dee2e6",
          "base-content": "#212529",
          "info": "#17a2b8",
          "info-content": "#ffffff",
          "success": "#28a745",
          "success-content": "#ffffff",
          "warning": "#ffa726",
          "warning-content": "#1f2937",
          "error": "#dc3545",
          "error-content": "#ffffff",
        },
      },
      {
        // TUMS Dark Theme
        "tums-dark": {
          "primary": "#4d6f62",
          "primary-content": "#ffffff",
          "secondary": "#c9a570",
          "secondary-content": "#1a1a1a",
          "accent": "#3d5a4f",
          "accent-content": "#ffffff",
          "neutral": "#9ca3af",
          "neutral-content": "#1a1a1a",
          "base-100": "#1a1a2e",
          "base-200": "#16162a",
          "base-300": "#0f0f1a",
          "base-content": "#e5e7eb",
          "info": "#3abff8",
          "info-content": "#002b3d",
          "success": "#36d399",
          "success-content": "#003320",
          "warning": "#fbbd23",
          "warning-content": "#382800",
          "error": "#f87272",
          "error-content": "#470000",
        },
      },
    ],
    darkTheme: "tums-dark",
    base: true,
    styled: true,
    utils: true,
    rtl: true,
    logs: false,
  },
}
